model:
  name: 'dino'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 224
  width: 224
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/dino_market1501_softmax'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train: # warm up schedule with sgd is better, warm up with cosine
  optim: 'sgd' # change it
  lr: 0.004
  max_epoch: 50
  batch_size: 32
  fixbase_epoch: 999
  open_layers: ['classifier']
  lr_scheduler: 'warm_up_cosine' # change it
  warm_up_epochs: 10
  stepsize: [20]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False